name: Deploy React Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            
            echo "=== 🚀 Triển khai Frontend React (Vite, port 5173) ==="

            cd /home/utc/library-management-fe

            echo ">>> Pull code mới nhất"
            git reset --hard
            git pull origin main

            echo ">>> Stop & remove container cũ"
            docker stop library-management || true
            docker rm library-management || true
            docker rmi library-management:latest || true

            echo ">>> Build Docker image mới"
            docker build -t library-management:latest .

            echo ">>> Run container mới (port 5173)"
            docker run -d \
              --name library-management \
              -p 5173:5173 \
              library-management:latest

            echo "✅ Deploy v3 thành công! App đang chạy tại http://<server-ip>:5173"
